name: hungergames
version: '${version}'
main: com.mcfrens.HungerGames
api-version: '1.20'

commands:
  starthungergames:
    description: Starts the Hunger Games
    usage: /<command>
    permission: op
