name: hungergames
version: '${version}'
main: com.mcfrens.HungerGames
api-version: '1.20.4'

commands:
  starthungergames:
    description: Starts the Hunger Games
    usage: /<command>
    permission: op
  endhungergames:
      description: Ends the Hunger Games
      usage: /<command>
      permission: op
  addstartlocation:
    description: Adds start location for Hunger Games
    usage: /<command>
    permission: op
  resetstartlocations:
    description: Removes all start locations for Hunger Games
    usage: /<command>
    permission: op
  resetchestlocations:
    description: Removes all chest locations for Hunger Games
    usage: /<command>
    permission: op
  addchestlocation:
    description: Adds a common chest location for Hunger Games
    usage: /<command>
    permission: op
  addallchestlocations:
    description: Adds a common chest location for Hunger Games for all chests found in surrounding chunk
    usage: /<command>
    permission: op
  resetfireworklocations:
    description: Removes all firework locations for Hunger Games
    usage: /<command>
    permission: op
  addfireworklocation:
    description: Adds a firework location for Hunger Games
    usage: /<command>
    permission: op
